version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bcare-app
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_URL=https://taminattcom.pro
      - DB_HOST=127.0.0.1
      - DB_DATABASE=u116650566_bcare
      - DB_USERNAME=u116650566_bcare
      - DB_PASSWORD=Reeree12.R.
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    networks:
      - bcare-network

  webserver:
    image: nginx:alpine
    container_name: bcare-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - bcare-network

networks:
  bcare-network:
    driver: bridge
