name: Deploy to Hostinger
on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      FTP_PASSWORD: ${{ secrets.HOSTINGER_PASSWORD }}

    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, bcmath, zip, gd, curl, soap, opcache
        ini-values: |
          memory_limit=1536M
          max_execution_time=300
          opcache.enable=1
          opcache.memory_consumption=128
        coverage: none
        tools: composer:v2

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install NPM dependencies
      run: npm install

    - name: Build assets
      run: npm run build

    - name: Install Composer dependencies
      run: |
        composer install --no-dev --optimize-autoloader --no-interaction
        composer dump-autoload --optimize

    - name: Prepare deployment
      run: |
        echo "Creating deployment package..."
        mkdir -p deployment
        cp -r app bootstrap config database lang public resources routes storage vendor composer.json composer.lock artisan deployment/
        cp .env.production deployment/.env

    - name: Set up deployment scripts
      run: |
        mkdir -p deployment/scripts
        cp scripts/deploy.sh deployment/scripts/
        cp scripts/verify_deployment.sh deployment/scripts/
        chmod +x deployment/scripts/*.sh

    - name: Configure nginx
      run: |
        mkdir -p deployment/nginx
        cp nginx/app.conf deployment/nginx/

    - name: 📂 Deploy to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 92.113.19.110
        username: u116650566.taminattcom.pro
        password: ${{ env.FTP_PASSWORD }}
        server-dir: /public_html/
        local-dir: ./deployment/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          tests/**
          phpunit.xml
          README.md
          .editorconfig
          .styleci.yml
          storage/framework/cache/**
          storage/framework/sessions/**
          storage/framework/views/**
          storage/logs/**

    - name: Execute deployment script
      uses: appleboy/ssh-action@master
      with:
        host: 92.113.19.110
        username: u116650566.taminattcom.pro
        password: ${{ env.FTP_PASSWORD }}
        script: |
          cd /public_html
          bash scripts/deploy.sh

    - name: Verify deployment
      run: bash scripts/verify_deployment.sh

    - name: Cleanup deployment files
      if: always()
      run: rm -rf deployment

    - name: Notify on success
      if: success()
      run: |
        echo "✅ Deployment successful to https://taminattcom.pro"
        echo "✅ Website is also accessible at https://www.taminattcom.pro"

    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Deployment failed"
