name: Deploy to Hostinger
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your-docker-username/bcare-insurance:latest

      - name: Deploy to Hostinger
        uses: appleboy/ssh-action@master
        with:
          host: 92.113.19.110
          username: u116650566
          password: ${{ secrets.SSH_PASSWORD }}
          port: 65002
          script: |
            cd ~/domains/taminattcom.pro
            docker-compose pull
            docker-compose up -d
